#!/usr/bin/env sh

# Includes assume pwd is diretory of build-protos script.
cd "$(dirname "$0")"

protoc --dart_out=./lib/generated ./protos/*
protoc --swift_out=./ios/Classes ./protos/*
protoc --swift_out=./macos/Classes ./protos/*
protoc --js_out=import_style=browser:./web/generated ./protos/*
