name: beatscratch_flutter_redux
description: BeatScratch for Flutter
publish_to: none

version: 1.0.9+266

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  js: ^0.6.2
  http: ^0.12.2
  protobuf: ^1.1.0
  unification: ^0.1.15
  uuid: ^2.0.4
  package_info_plus: ^0.6.3
  recase: ^3.0.0
  vibration: ^1.7.2
  share: ^0.6.5+4
  flutter_reorderable_list: ^1.0.0
    # path: ../flutter_reorderable_list
  url_launcher: ^5.7.10
  implicitly_animated_reorderable_list: 0.3.2
  #      path: ../implicitly_animated_reorderable_list
  flutter_keyboard_visibility: ^2.0.0
  aeyrium_sensor: ^1.0.7
#    path: ../aeyrium-sensor
  sensors: '>=0.4.1+10 <2.0.0'
#    path: ../flutter-plugins/packages/sensors
#  firebase_core: ^0.4.4+3
#  firebase_analytics: ^5.0.2
#  firebase_auth: ^0.15.5+3
#  google_sign_in: 4.3.0
#  cloud_firestore: 0.13.4+2
  dart_midi: 1.0.1
  quiver: ^2.1.3
  path_drawing: 0.4.1
  path_provider: ^1.6.24
  shared_preferences: ^0.5.12+4
#  file_picker: ^1.9.0
  # file_picker_cross: ^4.2.6
#  hive: ^1.4.1+1
  base_x: ^1.0.1
  archive: ^2.0.13
  font_awesome_flutter: ^8.11.0

  #  reorderables: 0.2.12

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluro: "^1.6.3"
  flutter_appavailability: ^0.0.21
  native_device_orientation: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: VulfSans
      fonts:
        - asset: assets/fonts/vulf_sans_medium.otf
        - asset: assets/fonts/vulf_sans_light.otf
          weight: 200
        - asset: assets/fonts/vulf_sans_regular.otf
          weight: 500
        - asset: assets/fonts/vulf_sans_bold.otf
          weight: 700
        - asset: assets/fonts/vulf_sans_black.otf
          weight: 800
