import 'dart:io';
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:uuid/uuid.dart';
import 'package:flutter/rendering.dart';

import 'dart:async';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/services.dart';
import 'package:vibration/vibration.dart';

class MyFlatButton extends FlatButton {
  const MyFlatButton({
    Key key,
    @required VoidCallback onPressed,
    VoidCallback onLongPress,
    ValueChanged<bool> onHighlightChanged,
    MouseCursor mouseCursor = SystemMouseCursors.basic,
    ButtonTextTheme textTheme,
    Color textColor,
    Color disabledTextColor,
    Color color,
    Color disabledColor,
    Color focusColor,
    Color hoverColor,
    Color highlightColor,
    Color splashColor,
    Brightness colorBrightness,
    EdgeInsetsGeometry padding,
    VisualDensity visualDensity,
    ShapeBorder shape,
    Clip clipBehavior = Clip.none,
    FocusNode focusNode,
    bool autofocus = false,
    MaterialTapTargetSize materialTapTargetSize,
    @required Widget child,
  }) : assert(clipBehavior != null),
      assert(autofocus != null),
      super(
      key: key,
      onPressed: onPressed,
      onLongPress: onLongPress,
      onHighlightChanged: onHighlightChanged,
      mouseCursor: mouseCursor,
      textTheme: textTheme,
      textColor: textColor,
      disabledTextColor: disabledTextColor,
      color: color,
      disabledColor: disabledColor,
      focusColor: focusColor,
      hoverColor: hoverColor,
      highlightColor: highlightColor,
      splashColor: splashColor,
      colorBrightness: colorBrightness,
      padding: padding,
      visualDensity: visualDensity,
      shape: shape,
      clipBehavior: clipBehavior,
      focusNode: focusNode,
      autofocus: autofocus,
      materialTapTargetSize: materialTapTargetSize,
      child: child,
    );
}

class MyRaisedButton extends RaisedButton {
  const MyRaisedButton({
    Key key,
    @required VoidCallback onPressed,
    VoidCallback onLongPress,
    ValueChanged<bool> onHighlightChanged,
    MouseCursor mouseCursor = SystemMouseCursors.basic,
    ButtonTextTheme textTheme,
    Color textColor,
    Color disabledTextColor,
    Color color,
    Color disabledColor,
    Color focusColor,
    Color hoverColor,
    Color highlightColor,
    Color splashColor,
    Brightness colorBrightness,
    double elevation,
    double focusElevation,
    double hoverElevation,
    double highlightElevation,
    double disabledElevation,
    EdgeInsetsGeometry padding,
    VisualDensity visualDensity,
    ShapeBorder shape,
    Clip clipBehavior = Clip.none,
    FocusNode focusNode,
    bool autofocus = false,
    MaterialTapTargetSize materialTapTargetSize,
    Duration animationDuration,
    Widget child,
  }) : assert(autofocus != null),
      assert(elevation == null || elevation >= 0.0),
      assert(focusElevation == null || focusElevation >= 0.0),
      assert(hoverElevation == null || hoverElevation >= 0.0),
      assert(highlightElevation == null || highlightElevation >= 0.0),
      assert(disabledElevation == null || disabledElevation >= 0.0),
      assert(clipBehavior != null),
      super(
      key: key,
      onPressed: onPressed,
      onLongPress: onLongPress,
      onHighlightChanged: onHighlightChanged,
      mouseCursor: mouseCursor,
      textTheme: textTheme,
      textColor: textColor,
      disabledTextColor: disabledTextColor,
      color: color,
      disabledColor: disabledColor,
      focusColor: focusColor,
      hoverColor: hoverColor,
      highlightColor: highlightColor,
      splashColor: splashColor,
      colorBrightness: colorBrightness,
      elevation: elevation,
      focusElevation: focusElevation,
      hoverElevation: hoverElevation,
      highlightElevation: highlightElevation,
      disabledElevation: disabledElevation,
      padding: padding,
      visualDensity: visualDensity,
      shape: shape,
      clipBehavior: clipBehavior,
      focusNode: focusNode,
      autofocus: autofocus,
      materialTapTargetSize: materialTapTargetSize,
      animationDuration: animationDuration,
      child: child,
    );
}

class MySlider extends Slider {
  const MySlider({
    Key key,
    @required double value,
    @required ValueChanged<double> onChanged,
    ValueChanged<double> onChangeStart,
    ValueChanged<double> onChangeEnd,
    double min = 0.0,
    double max = 1.0,
    int divisions,
    String label,
    Color activeColor,
    Color inactiveColor,
    MouseCursor mouseCursor = SystemMouseCursors.basic,
    SemanticFormatterCallback semanticFormatterCallback,
    FocusNode focusNode,
    bool autofocus = false,
  }) : super(
    key: key,
    value: value,
    onChanged: onChanged,
    onChangeStart: onChangeStart,
    onChangeEnd: onChangeEnd,
    min: min,
    max: max,
    divisions: divisions,
    label: label,
    activeColor: activeColor,
    inactiveColor: inactiveColor,
    mouseCursor: mouseCursor,
    semanticFormatterCallback: semanticFormatterCallback,
    focusNode: focusNode,
    autofocus: autofocus,
  );
}

class MyPopupMenuItem<T> extends PopupMenuItem<T> {
  const MyPopupMenuItem({
    Key key,
    T value,
    bool enabled = true,
    double height = kMinInteractiveDimension,
    TextStyle textStyle,
    MouseCursor mouseCursor = SystemMouseCursors.basic,
    @required Widget child,
  }) : super(
    key: key,
    value: value,
    enabled: enabled,
    height: height,
    textStyle: textStyle,
    mouseCursor: mouseCursor,
    child: child,
  );
}